// Copyright (C) the libgit2 contributors. All rights reserved.
// C# adaptation Copyright (c) 2026 LibGit2CS contributors.
// Licensed under GNU GPL v2 only with the libgit2 linking exception.
// See LICENSE and THIRD-PARTY-NOTICES.txt at the repository root.
// Adapted from libgit2 v1.9.4 (f7164261c9bc0a7e0ebf767c584e5192810a8b24).

namespace LibGit2CS.Core;

/// <summary>
/// libgit2 return codes. Maps 1:1 to <c>git_error_code</c> in <c>include/git2/errors.h</c>.
/// Negative values are errors; zero is success.
/// </summary>
/// <remarks>
/// In the managed port, error codes ride on <see cref="GitException"/>; they are not
/// function return values. The enum is preserved verbatim for fidelity with libgit2
/// and for consumers that switch on <see cref="GitException.Code"/>.
/// </remarks>
public enum GitErrorCode
{
    /// <summary>No error occurred; the call was successful. (<c>GIT_OK = 0</c>)</summary>
    Ok = 0,

    /// <summary>An error occurred. (<c>GIT_ERROR = -1</c>)</summary>
    Error = -1,

    /// <summary>Requested object could not be found. (<c>GIT_ENOTFOUND = -3</c>)</summary>
    NotFound = -3,

    /// <summary>Object exists preventing operation. (<c>GIT_EEXISTS = -4</c>)</summary>
    Exists = -4,

    /// <summary>More than one object matches. (<c>GIT_EAMBIGUOUS = -5</c>)</summary>
    Ambiguous = -5,

    /// <summary>Output buffer too short to hold data. (<c>GIT_EBUFS = -6</c>)</summary>
    BufferTooShort = -6,

    /// <summary>Sentinel from a user callback; never generated by libgit2. (<c>GIT_EUSER = -7</c>)</summary>
    User = -7,

    /// <summary>Operation not allowed on bare repository. (<c>GIT_EBAREREPO = -8</c>)</summary>
    BareRepo = -8,

    /// <summary>HEAD refers to branch with no commits. (<c>GIT_EUNBORNBRANCH = -9</c>)</summary>
    UnbornBranch = -9,

    /// <summary>Merge in progress prevented operation. (<c>GIT_EUNMERGED = -10</c>)</summary>
    Unmerged = -10,

    /// <summary>Reference was not fast-forwardable. (<c>GIT_ENONFASTFORWARD = -11</c>)</summary>
    NonFastForward = -11,

    /// <summary>Name/ref spec was not in a valid format. (<c>GIT_EINVALIDSPEC = -12</c>)</summary>
    InvalidSpec = -12,

    /// <summary>Checkout conflicts prevented operation. (<c>GIT_ECONFLICT = -13</c>)</summary>
    Conflict = -13,

    /// <summary>Lock file prevented operation. (<c>GIT_ELOCKED = -14</c>)</summary>
    Locked = -14,

    /// <summary>Reference value does not match expected. (<c>GIT_EMODIFIED = -15</c>)</summary>
    Modified = -15,

    /// <summary>Authentication error. (<c>GIT_EAUTH = -16</c>)</summary>
    Auth = -16,

    /// <summary>Server certificate is invalid. (<c>GIT_ECERTIFICATE = -17</c>)</summary>
    Certificate = -17,

    /// <summary>Patch/merge has already been applied. (<c>GIT_EAPPLIED = -18</c>)</summary>
    Applied = -18,

    /// <summary>The requested peel operation is not possible. (<c>GIT_EPEEL = -19</c>)</summary>
    Peel = -19,

    /// <summary>Unexpected EOF. (<c>GIT_EEOF = -20</c>)</summary>
    Eof = -20,

    /// <summary>Invalid operation or input. (<c>GIT_EINVALID = -21</c>)</summary>
    Invalid = -21,

    /// <summary>Uncommitted changes in index prevented operation. (<c>GIT_EUNCOMMITTED = -22</c>)</summary>
    Uncommitted = -22,

    /// <summary>The operation is not valid for a directory. (<c>GIT_EDIRECTORY = -23</c>)</summary>
    Directory = -23,

    /// <summary>A merge conflict exists and cannot continue. (<c>GIT_EMERGECONFLICT = -24</c>)</summary>
    MergeConflict = -24,

    /// <summary>A user-configured callback refused to act. (<c>GIT_PASSTHROUGH = -30</c>)</summary>
    PassThrough = -30,

    /// <summary>Signals end of iteration with iterator. (<c>GIT_ITEROVER = -31</c>)</summary>
    IterOver = -31,

    /// <summary>Internal only. (<c>GIT_RETRY = -32</c>)</summary>
    Retry = -32,

    /// <summary>Hashsum mismatch in object. (<c>GIT_EMISMATCH = -33</c>)</summary>
    Mismatch = -33,

    /// <summary>Unsaved changes in the index would be overwritten. (<c>GIT_EINDEXDIRTY = -34</c>)</summary>
    IndexDirty = -34,

    /// <summary>Patch application failed. (<c>GIT_EAPPLYFAIL = -35</c>)</summary>
    ApplyFail = -35,

    /// <summary>The object is not owned by the current user. (<c>GIT_EOWNER = -36</c>)</summary>
    Owner = -36,

    /// <summary>The operation timed out. (<c>GIT_TIMEOUT = -37</c>)</summary>
    Timeout = -37,

    /// <summary>There were no changes. (<c>GIT_EUNCHANGED = -38</c>)</summary>
    Unchanged = -38,

    /// <summary>An option is not supported. (<c>GIT_ENOTSUPPORTED = -39</c>)</summary>
    NotSupported = -39,

    /// <summary>The subject is read-only. (<c>GIT_EREADONLY = -40</c>)</summary>
    ReadOnly = -40,
}
