using LibGit2CS.Core;
using LibGit2CS.Refs;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Worktree;

/// <summary>
/// Golden tests for <see cref="LibGit2CS.Repository.Worktree.ListAsync"/> and
/// <see cref="LibGit2CS.Repository.Worktree.AddAsync"/>, comparing the C# worktree
/// enumeration output byte-exact against
/// <c>git worktree list --porcelain</c> captured in
/// <c>Fixtures/worktree/expected/worktree_*.txt</c>.
/// </summary>
/// <remarks>
/// The golden files are generated by <c>generate-goldens.sh</c>
/// (worktree section) which builds a repo with 2 commits,
/// adds worktrees via <c>git worktree add</c>, and captures
/// <c>git worktree list --porcelain</c>. Paths in both the golden and
/// C# output are normalized to <c>&lt;TEMP&gt;</c> before comparison.
/// </remarks>
public sealed class WorktreeGoldenTests : WorktreeGoldenBase
{
    [Fact]
    public async Task List_NoLinkedWorktrees_MatchesGitWorktreeList()
    {
        await using GitRepository repo = await CreateMainRepo();
        IReadOnlyList<LibGit2CS.Repository.Worktree> linked = await repo.WorktreeListAsync(TestContext.Current.CancellationToken);
        string actual = await WorktreeGoldenFormatter.FormatList(repo, linked);
        string normalized = NormalizeTempPaths(actual);
        string expected = LoadExpected("worktree_list_none");

        Assert.Equal(expected, normalized);
    }

    [Fact]
    public async Task List_OneLinkedWorktree_MatchesGitWorktreeList()
    {
        await using GitRepository repo = await CreateMainRepo();
        string wtPath = Path.Combine(TempDir, "wt1");
        await repo.WorktreeAddAsync("wt1", wtPath, cancellationToken: TestContext.Current.CancellationToken);

        IReadOnlyList<LibGit2CS.Repository.Worktree> linked = await repo.WorktreeListAsync(TestContext.Current.CancellationToken);
        string actual = await WorktreeGoldenFormatter.FormatList(repo, linked);
        string normalized = NormalizeTempPaths(actual);
        string expected = LoadExpected("worktree_list_one");

        Assert.Equal(expected, normalized);
    }

    [Fact]
    public async Task List_ThreeLinkedWorktrees_MatchesGitWorktreeList()
    {
        await using GitRepository repo = await CreateMainRepo();
        await repo.WorktreeAddAsync("wt1", Path.Combine(TempDir, "wt1"), cancellationToken: TestContext.Current.CancellationToken);
        await repo.WorktreeAddAsync("wt2", Path.Combine(TempDir, "wt2"), cancellationToken: TestContext.Current.CancellationToken);
        await repo.WorktreeAddAsync("wt3", Path.Combine(TempDir, "wt3"), cancellationToken: TestContext.Current.CancellationToken);

        IReadOnlyList<LibGit2CS.Repository.Worktree> linked = await repo.WorktreeListAsync(TestContext.Current.CancellationToken);
        string actual = await WorktreeGoldenFormatter.FormatList(repo, linked);
        string normalized = NormalizeTempPaths(actual);
        string expected = LoadExpected("worktree_list_three");

        Assert.Equal(expected, normalized);
    }

    [Fact]
    public async Task Lookup_ReturnsWorktreeWithCorrectProperties()
    {
        await using GitRepository repo = await CreateMainRepo();
        string wtPath = Path.Combine(TempDir, "wt1");
        await repo.WorktreeAddAsync("wt1", wtPath, cancellationToken: TestContext.Current.CancellationToken);

        LibGit2CS.Repository.Worktree? wt = await repo.WorktreeLookupAsync("wt1", TestContext.Current.CancellationToken);
        Assert.NotNull(wt);
        Assert.Equal("wt1", wt!.Name);
        Assert.Equal(wtPath.Replace('\\', '/'), wt.Path);
    }

    [Fact]
    public async Task Lock_ThenList_MatchesGitWorktreeList()
    {
        await using GitRepository repo = await CreateMainRepo();
        string wtPath = Path.Combine(TempDir, "wt1");
        LibGit2CS.Repository.Worktree wt = await repo.WorktreeAddAsync("wt1", wtPath, cancellationToken: TestContext.Current.CancellationToken);
        await wt.LockAsync("manual lock reason", TestContext.Current.CancellationToken);

        IReadOnlyList<LibGit2CS.Repository.Worktree> linked = await repo.WorktreeListAsync(TestContext.Current.CancellationToken);
        string actual = await WorktreeGoldenFormatter.FormatList(repo, linked);
        string normalized = NormalizeTempPaths(actual);
        string expected = LoadExpected("worktree_locked");

        Assert.Equal(expected, normalized);
    }

    [Fact]
    public async Task Add_CreatesBranchAndChecksOutFiles()
    {
        await using GitRepository repo = await CreateMainRepo();
        string wtPath = Path.Combine(TempDir, "wt1");
        await repo.WorktreeAddAsync("wt1", wtPath, cancellationToken: TestContext.Current.CancellationToken);

        // The worktree should have the committed files checked out.
        Assert.True(File.Exists(Path.Combine(wtPath, "file1.txt")));
        Assert.True(File.Exists(Path.Combine(wtPath, "file2.txt")));

        // The worktree repo should have HEAD pointing to refs/heads/wt1.
        await using GitRepository wtRepo = await GitRepository.OpenAsync(wtPath, new GitContext(), cancellationToken: TestContext.Current.CancellationToken);
        GitReference? head = await wtRepo.ReferenceLookupAsync("HEAD", cancellationToken: TestContext.Current.CancellationToken);
        Assert.NotNull(head);
        Assert.Equal("refs/heads/wt1", (head as GitSymbolicReference)?.TargetName);
    }
}
