using System.Text;

using LibGit2CS.Core;
using LibGit2CS.Refs;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Worktree;

/// <summary>
/// Serializes worktree state to text format compatible with
/// <c>git worktree list --porcelain</c>, so that worktree golden tests can
/// compare C# output byte-exact against golden files generated by
/// <c>generate-goldens.sh</c> (worktree section).
/// </summary>
/// <remarks>
/// The <c>git worktree list --porcelain</c> format is:
/// <code>
/// worktree &lt;path&gt;
/// HEAD &lt;oid&gt;
/// branch &lt;ref&gt;
/// locked &lt;reason&gt;    (only if locked)
///
/// </code>
/// Each worktree entry is separated by a blank line. The main worktree
/// always appears first. <see cref="Worktree.ListAsync"/> only returns linked
/// worktrees (not the main), so this formatter accepts the parent repo to
/// prepend the main worktree entry.
/// </remarks>
internal static class WorktreeGoldenFormatter
{
    /// <summary>
    /// Formats the worktree list (main + linked) as
    /// <c>git worktree list --porcelain</c> output.
    /// </summary>
    /// <param name="repo">The parent (main) repository.</param>
    /// <param name="linkedWorktrees">The linked worktrees from
    /// <see cref="LibGit2CS.Repository.Worktree.ListAsync"/>.</param>
    public static async Task<string> FormatList(GitRepository repo, IReadOnlyList<LibGit2CS.Repository.Worktree> linkedWorktrees)
    {
        ArgumentNullException.ThrowIfNull(repo);
        ArgumentNullException.ThrowIfNull(linkedWorktrees);

        var sb = new StringBuilder();

        // Main worktree first.
        await AppendWorktree(sb, repo.Workdir!.TrimEnd('/'), repo);
        sb.Append('\n');

        // Linked worktrees — sorted by name for stable output (matching
        // git's deterministic order: creation order = name order).
        var sorted = linkedWorktrees.OrderBy(wt => wt.Name, StringComparer.Ordinal).ToList();
        foreach (LibGit2CS.Repository.Worktree? wt in sorted)
        {
            await AppendWorktree(sb, wt.Path.TrimEnd('/'), await OpenWorktreeRepo(wt));
            sb.Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// Formats a single worktree entry (for the locked case where we want
    /// to show the main + one locked worktree).
    /// </summary>
    public static async Task<string> FormatListWithLock(
        GitRepository repo,
        IReadOnlyList<LibGit2CS.Repository.Worktree> linkedWorktrees)
    {
        return await FormatList(repo, linkedWorktrees);
    }

    private static async ValueTask AppendWorktree(StringBuilder sb, string path, GitRepository wtRepo)
    {
        sb.Append("worktree ");
        sb.Append(path);
        sb.Append('\n');

        // HEAD line — always present (resolved OID).
        GitReference? headResolved = await wtRepo.ReferenceResolveAsync("HEAD");
        if (headResolved is GitDirectReference direct)
        {
            sb.Append("HEAD ");
            sb.Append(direct.Target);
            sb.Append('\n');
        }

        // Branch line — present when HEAD is a symbolic ref to a branch.
        // We need to read HEAD as a symbolic ref (not resolved) to get the
        // branch name. Use Lookup to get the raw HEAD reference.
        GitReference? headRaw = await wtRepo.ReferenceLookupAsync("HEAD");
        if (headRaw is GitSymbolicReference sym)
        {
            sb.Append("branch ");
            sb.Append(sym.TargetName);
            sb.Append('\n');
        }

        // Locked line — check the worktree admin dir for a `locked` file.
        // For the main worktree, there's no locked file.
        string lockedFile = Path.Combine(wtRepo.Path, "locked");
        if (File.Exists(lockedFile))
        {
            sb.Append("locked");
            string reason = (await File.ReadAllTextAsync(lockedFile, cancellationToken: TestContext.Current.CancellationToken)).Trim();
            if (!string.IsNullOrEmpty(reason))
            {
                sb.Append(' ');
                sb.Append(reason);
            }
            sb.Append('\n');
        }
    }

    private static async ValueTask<GitRepository> OpenWorktreeRepo(LibGit2CS.Repository.Worktree wt)
    {
        return await GitRepository.OpenAsync(wt.Path, new GitContext());
    }
}
