// Copyright (C) the libgit2 contributors. All rights reserved.
// C# adaptation Copyright (c) 2026 LibGit2CS contributors.
// Licensed under GNU GPL v2 only with the libgit2 linking exception.
// See LICENSE and THIRD-PARTY-NOTICES.txt at the repository root.
// Adapted from libgit2 v1.9.4 (f7164261c9bc0a7e0ebf767c584e5192810a8b24).

using System.Diagnostics.CodeAnalysis;
using System.Text;

using LibGit2CS.Core;
using LibGit2CS.Core.Hashing;
using LibGit2CS.Remote;

namespace LibGit2CS.Transports;

/// <summary>
/// Parses and writes git pkt-line protocol packets.
/// Managed port of <c>src/libgit2/transports/smart_pkt.c</c>.
/// </summary>
public static class GitPacketReader
{
    /// <summary>Size of the 4-hex-digit length prefix.</summary>
    public const int PktLenSize = 4;

    /// <summary>Maximum pkt-line length (0xffff - 0 = 65535; but practical max is 65520 for side-band-64k).</summary>
    public const int PktMaxSize = 0xffff;

    /// <summary>Side-band channel identifiers (first byte of data packets).</summary>
    public const byte SideBandData = 0x01;

    /// <summary>Side-band progress channel.</summary>
    public const byte SideBandProgress = 0x02;

    /// <summary>Side-band error channel.</summary>
    public const byte SideBandError = 0x03;

    /// <summary>Flush packet literal: "0000".</summary>
    public static ReadOnlySpan<byte> FlushStrBytes => "0000"u8;

    /// <summary>Done packet literal: "0009done\n".</summary>
    public static ReadOnlySpan<byte> DoneStrBytes => "0009done\n"u8;

    /// <summary>Delim packet literal: "0001" (protocol v2 only, not generated by v0/v1).</summary>
    public const string DelimStr = "0001";

    /// <summary>
    /// Parse the 4-hex-digit length prefix from the start of a pkt-line buffer.
    /// Ported from <c>parse_len()</c> in <c>smart_pkt.c:524</c>.
    /// </summary>
    /// <param name="buffer">The buffer to read from.</param>
    /// <param name="length">[out] The decoded length (total pkt-line length including the 4-byte prefix). 0 = flush packet.</param>
    /// <returns><c>true</c> if the length was parsed; <c>false</c> if the buffer is too short (&lt; 4 bytes).</returns>
    /// <exception cref="GitException">If the length prefix contains invalid hex digits.</exception>
    public static bool TryParseLength(ReadOnlySpan<byte> buffer, out int length)
    {
        length = 0;

        if (buffer.Length < PktLenSize)
        {
            return false; // GIT_EBUFS — not enough data yet
        }

        // Validate all 4 chars are hex digits
        for (int i = 0; i < PktLenSize; i++)
        {
            if (!IsHexDigit((char)buffer[i]))
            {
                // C (smart_pkt.c:594-597): git_pkt_parse_line overwrites
                // parse_len's "invalid hex digit" message — the final error
                // is "unexpected pack file" for a raw "PACK" prefix,
                // otherwise "bad packet length" (GIT_ERROR, -1). The port
                // used to surface parse_len's intermediate message with
                // GitErrorCode.Invalid.
                throw new GitException(
                    GitErrorCode.Error,
                    buffer.StartsWith("PACK"u8) ? "unexpected pack file" : "bad packet length",
                    GitErrorCategory.Net);
            }
        }

        // Parse 4 hex digits
        length = (HexValue(buffer[0]) << 12) |
                 (HexValue(buffer[1]) << 8) |
                 (HexValue(buffer[2]) << 4) |
                 HexValue(buffer[3]);

        return true;
    }

    /// <summary>
    /// Parse a single pkt-line from the buffer.
    /// Ported from <c>git_pkt_parse_line()</c> in <c>smart_pkt.c:575</c>.
    /// </summary>
    /// <param name="buffer">The byte buffer to parse from.</param>
    /// <param name="consumed">[out] Number of bytes consumed from the buffer.</param>
    /// <param name="state">[in/out] Parsing context (OID type + capability state).</param>
    /// <returns>The parsed <see cref="GitPacket"/>.</returns>
    /// <exception cref="GitException">If the packet is malformed.</exception>
    public static GitPacket Parse(ReadOnlySpan<byte> buffer, out int consumed, ref GitPacketParseState state)
    {
        consumed = 0;

        if (!TryParseLength(buffer, out int len))
        {
            throw new GitException(GitErrorCode.BufferTooShort, "not enough data for pkt-line length", GitErrorCategory.Net);
        }

        // Check if we have the full pkt-line
        if (buffer.Length < len)
        {
            throw new GitException(GitErrorCode.BufferTooShort, "not enough data for full pkt-line", GitErrorCategory.Net);
        }

        // len == 0 is a flush packet
        if (len == 0)
        {
            consumed = PktLenSize;
            return new GitFlushPacket();
        }

        // Length must be >= PktLenSize (4); values 1-3 are invalid.
        // C (smart_pkt.c:613-615): a bare GIT_ERROR (-1) with no message.
        if (len < PktLenSize)
        {
            throw new GitException(GitErrorCode.Error, $"invalid pkt-line length: {len}", GitErrorCategory.Net);
        }

        // Length == 4 means empty packet (no payload) — invalid in git protocol.
        // C (smart_pkt.c:617-621): "Invalid empty packet", GIT_ERROR (-1).
        if (len == PktLenSize)
        {
            throw new GitException(GitErrorCode.Error, "Invalid empty packet", GitErrorCategory.Net);
        }

        // Skip past the 4-byte length prefix
        int payloadLen = len - PktLenSize;
        ReadOnlySpan<byte> payload = buffer.Slice(PktLenSize, payloadLen);

        consumed = len;

        return ParsePayload(payload, payloadLen, ref state);
    }

    /// <summary>
    /// Attempt to parse a single pkt-line without throwing. Returns
    /// <c>false</c> for both the retryable underrun (<see cref="GitPacketParseError.BufferTooShort"/>)
    /// and fatal parse failures (<see cref="GitPacketParseError.InvalidLength"/>,
    /// <see cref="GitPacketParseError.InvalidPayload"/>); the specific outcome is
    /// reported via <paramref name="error"/>. The caller's policy is explicit:
    /// <c>false</c> + <see cref="GitPacketParseError.BufferTooShort"/> → refill
    /// and retry; <c>false</c> + anything else → the caller throws.
    /// Mirrors the <c>GIT_EBUFS</c>-vs-fatal branching of <c>git_pkt_parse_line</c>
    /// (<c>smart_pkt.c</c>) surfaced as a value rather than a thrown exception, so
    /// the common partial-read path (e.g. SSH rekey fragmenting a pkt-line) does
    /// not pay exception-construction cost.
    /// </summary>
    /// <param name="buffer">The byte buffer to parse from.</param>
    /// <param name="packet">[out] The parsed packet when this method returns <c>true</c>.</param>
    /// <param name="consumed">[out] Number of bytes consumed from the buffer.</param>
    /// <param name="error">[out] Outcome category. <see cref="GitPacketParseError.None"/> on success.</param>
    /// <param name="state">[in/out] Parsing context (OID type + capability state).</param>
    /// <returns><c>true</c> if a packet was parsed; <c>false</c> if more data is needed or the input is corrupt.</returns>
    public static bool TryParse(
        ReadOnlySpan<byte> buffer,
        [NotNullWhen(true)] out GitPacket? packet,
        out int consumed,
        out GitPacketParseError error,
        ref GitPacketParseState state)
    {
        packet = null;
        consumed = 0;
        error = GitPacketParseError.None;

        // Length prefix not yet fully available — retry signal.
        if (buffer.Length < PktLenSize)
        {
            error = GitPacketParseError.BufferTooShort;
            return false;
        }

        // Invalid hex digit in the length prefix.
        if (!TryDecodeLength(buffer, out int len))
        {
            error = GitPacketParseError.InvalidHexLength;
            return false;
        }

        // Full pkt-line payload not yet available — retry signal.
        if (buffer.Length < len)
        {
            error = GitPacketParseError.BufferTooShort;
            return false;
        }

        // Flush packet.
        if (len == 0)
        {
            consumed = PktLenSize;
            packet = new GitFlushPacket();
            return true;
        }

        // Length must be >= PktLenSize (4); values 1-3 are invalid.
        if (len < PktLenSize)
        {
            error = GitPacketParseError.InvalidLength;
            return false;
        }

        // Length == 4 means empty packet (no payload) — invalid in git protocol.
        if (len == PktLenSize)
        {
            error = GitPacketParseError.InvalidEmptyPacket;
            return false;
        }

        int payloadLen = len - PktLenSize;
        ReadOnlySpan<byte> payload = buffer.Slice(PktLenSize, payloadLen);

        try
        {
            packet = ParsePayload(payload, payloadLen, ref state);
        }
        catch (GitException)
        {
            // Payload-level corruption (bad ACK / REF / shallow / report-status).
            // Surfaced as a value so TryParse never throws; the caller decides
            // whether to throw. This catch is cold-path only (genuine corruption).
            error = GitPacketParseError.InvalidPayload;
            return false;
        }

        consumed = len;
        return true;
    }

    /// <summary>
    /// Decode the 4-hex-digit length prefix, returning <c>false</c> (without
    /// throwing) on an invalid hex digit. Unlike <see cref="TryParseLength"/>,
    /// which throws on invalid hex, this is the non-throwing variant used by
    /// <see cref="TryParse"/> so that length corruption is reported as a value.
    /// </summary>
    /// <param name="buffer">A buffer of at least <see cref="PktLenSize"/> bytes.</param>
    /// <param name="length">[out] The decoded length including the 4-byte prefix. 0 = flush packet.</param>
    /// <returns><c>true</c> if all 4 bytes are valid hex digits; <c>false</c> otherwise.</returns>
    private static bool TryDecodeLength(ReadOnlySpan<byte> buffer, out int length)
    {
        length = 0;

        for (int i = 0; i < PktLenSize; i++)
        {
            if (!IsHexDigit((char)buffer[i]))
            {
                return false;
            }
        }

        length = (HexValue(buffer[0]) << 12) |
                 (HexValue(buffer[1]) << 8) |
                 (HexValue(buffer[2]) << 4) |
                 HexValue(buffer[3]);

        return true;
    }

    private static GitPacket ParsePayload(ReadOnlySpan<byte> payload, int len, ref GitPacketParseState state)
    {
        if (len == 0)
        {
            throw new GitException(GitErrorCode.Invalid, "empty packet payload", GitErrorCategory.Net);
        }

        byte first = payload[0];

        // Side-band channels: check first byte
        if (first == SideBandData)
        {
            return new GitDataPacket(payload[1..].ToArray());
        }

        if (first == SideBandProgress)
        {
            return new GitProgressPacket(payload[1..].ToArray());
        }

        if (first == SideBandError)
        {
            string msg = Encoding.UTF8.GetString(payload[1..]);
            return new GitErrorPacket(msg);
        }

        // String-prefix dispatch. C (smart_pkt.c:639-658) dispatches on the
        // SHORT prefixes ("ERR", "ok", "ng", "shallow", "unshallow") and only
        // the specific parser requires the trailing space — so "ERRfoo" /
        // "okfoo" / "ngfoo" / "shallowfoo" route to the ERR/OK/NG/shallow
        // parsers and fail with their messages.
        // "ERR " / "ok " / "ng " and fell through to the REF parser instead.
        if (StartsWith(payload, "ACK"u8))
        {
            return ParseAck(payload, len, ref state);
        }

        if (StartsWith(payload, "NAK"u8))
        {
            return new GitNakPacket();
        }

        if (StartsWith(payload, "ERR"u8))
        {
            return ParseErr(payload);
        }

        if (first == (byte)'#')
        {
            return new GitCommentPacket(Encoding.UTF8.GetString(payload));
        }

        if (StartsWith(payload, "ok"u8))
        {
            return ParseOk(payload);
        }

        if (StartsWith(payload, "ng"u8))
        {
            return ParseNg(payload);
        }

        if (StartsWith(payload, "unpack"u8))
        {
            return ParseUnpack(payload);
        }

        if (StartsWith(payload, "shallow"u8))
        {
            return ParseShallow(payload, len, ref state, isShallow: true);
        }

        if (StartsWith(payload, "unshallow"u8))
        {
            return ParseShallow(payload, len, ref state, isShallow: false);
        }

        // Fallback: reference advertisement
        return ParseRef(payload, len, ref state);
    }

    /// <summary>
    /// Parse an "ERR &lt;message&gt;" packet. Ported from <c>err_pkt()</c>
    /// in <c>smart_pkt.c:128</c> — the space after "ERR" is required, else
    /// "error parsing ERR pkt-line".
    /// </summary>
    private static GitErrorPacket ParseErr(ReadOnlySpan<byte> payload)
    {
        if (!StartsWith(payload, "ERR "u8))
        {
            throw new GitException(GitErrorCode.Error, "error parsing ERR pkt-line", GitErrorCategory.Net);
        }

        return new GitErrorPacket(Encoding.UTF8.GetString(payload[4..]));
    }

    private static GitAckPacket ParseAck(ReadOnlySpan<byte> payload, int _, ref GitPacketParseState state)
    {
        // C (smart_pkt.c:61-64): ack_pkt requires the "ACK " prefix (with space) before slicing — "ACK"/"ACKX..." fail with "error parsing ACK pkt-line".
        if (!StartsWith(payload, "ACK "u8))
        {
            throw new GitException(GitErrorCode.Error, "error parsing ACK pkt-line", GitErrorCategory.Net);
        }

        // "ACK <oid>[ <status>]"
        // Skip "ACK "
        ReadOnlySpan<byte> rest = payload[4..];
        int oidHexSize = GitOid.HexSizeFor(state.OidType);

        if (rest.Length < oidHexSize)
        {
            throw new GitException(GitErrorCode.Error, "error parsing ACK pkt-line", GitErrorCategory.Net);
        }

        // Parse OID
        ReadOnlySpan<byte> oidHex = rest[..oidHexSize];
        GitOid oid = ParseOidHex(oidHex, state.OidType, "error parsing ACK pkt-line");
        rest = rest[oidHexSize..];

        GitAckStatus status = GitAckStatus.None;

        if (rest.Length > 0 && rest[0] == (byte)' ')
        {
            rest = rest[1..]; // skip space

            if (StartsWith(rest, "continue"u8))
            {
                status = GitAckStatus.Continue;
            }
            else if (StartsWith(rest, "common"u8))
            {
                status = GitAckStatus.Common;
            }
            else if (StartsWith(rest, "ready"u8))
            {
                status = GitAckStatus.Ready;
            }
            else
            {
                throw new GitException(GitErrorCode.Error, "error parsing ACK pkt-line", GitErrorCategory.Net);
            }
        }

        return new GitAckPacket(oid, status);
    }

    private static GitOkPacket ParseOk(ReadOnlySpan<byte> payload)
    {
        // "ok <ref>\n" — the space after "ok" is required (C ok_pkt,
        // smart_pkt.c:361-368): "okfoo" fails with
        // "error parsing OK pkt-line".
        if (!StartsWith(payload, "ok "u8))
        {
            throw new GitException(GitErrorCode.Error, "error parsing OK pkt-line", GitErrorCategory.Net);
        }

        ReadOnlySpan<byte> rest = payload[3..]; // skip "ok "

        // Strip trailing newline
        if (rest.Length > 0 && rest[^1] == (byte)'\n')
        {
            rest = rest[..^1];
        }

        return new GitOkPacket(Encoding.UTF8.GetString(rest));
    }

    private static GitNgPacket ParseNg(ReadOnlySpan<byte> payload)
    {
        // C (smart_pkt.c:389-391): ng_pkt requires the "ng " prefix (with space) before slicing — "ng"/"ngX..." fail with "invalid packet line".
        if (!StartsWith(payload, "ng "u8))
        {
            throw new GitException(GitErrorCode.Error, "invalid packet line", GitErrorCategory.Net);
        }

        // "ng <ref> <msg>\n"
        ReadOnlySpan<byte> rest = payload[3..]; // skip "ng "

        // Find space separating ref and message
        int space = rest.IndexOf((byte)' ');
        if (space < 0)
        {
            throw new GitException(GitErrorCode.Error, "invalid packet line", GitErrorCategory.Net);
        }

        string refName = Encoding.UTF8.GetString(rest[..space]);

        ReadOnlySpan<byte> after = rest[(space + 1)..];

        // C (smart_pkt.c:405-410): the message must be terminated by '\n' -
        // "ng refs/heads/x oops" (no newline) is an "invalid packet line".
        int nl = after.IndexOf((byte)'\n');
        if (nl < 0)
        {
            throw new GitException(GitErrorCode.Error, "invalid packet line", GitErrorCategory.Net);
        }

        string msg = Encoding.UTF8.GetString(after[..nl]);

        return new GitNgPacket(refName, msg);
    }

    private static GitUnpackPacket ParseUnpack(ReadOnlySpan<byte> payload)
    {
        // "unpack ok" or "unpack <error>"
        if (StartsWith(payload, "unpack ok"u8))
        {
            return new GitUnpackPacket(true);
        }

        // Any other "unpack ..." is an error

        // The message is the error
        return new GitUnpackPacket(false);
    }

    private static GitPacket ParseShallow(ReadOnlySpan<byte> payload, int _, ref GitPacketParseState state, bool isShallow)
    {
        // C (smart_pkt.c:462-466, 501-505): shallow_pkt/unshallow_pkt require the "shallow "/"unshallow " prefix (with space) before slicing —
        // truncated/space-less payloads fail with "invalid packet line".
        if (!StartsWith(payload, isShallow ? "shallow "u8 : "unshallow "u8))
        {
            throw new GitException(GitErrorCode.Error, "invalid packet line", GitErrorCategory.Net);
        }

        // "shallow <oid>" or "unshallow <oid>"
        int prefixLen = isShallow ? "shallow ".Length : "unshallow ".Length;
        ReadOnlySpan<byte> rest = payload[prefixLen..];

        int oidHexSize = GitOid.HexSizeFor(state.OidType);

        // C (smart_pkt.c:446-522): the payload after the prefix must be
        // EXACTLY the OID hex length — trailing bytes are "invalid packet
        // line".
        if (rest.Length != oidHexSize)
        {
            throw new GitException(GitErrorCode.Error, "invalid packet line", GitErrorCategory.Net);
        }

        // C's
        // shallow_pkt ignores git_oid__fromstr's failure and keeps the
        // ZEROED oid (smart_pkt.c:478; git_oid__fromstrn zeroes the oid
        // before failing, oid.c:50) — non-hex shallow OIDs are ACCEPTED.
        GitOid oid = ParseOidHex(rest, state.OidType, errorMessage: null);

        return isShallow
            ? new GitShallowPacket(oid)
            : new GitUnshallowPacket(oid);
    }

    private static GitRefPacket ParseRef(ReadOnlySpan<byte> payload, int len, ref GitPacketParseState state)
    {
        // "<oid> <name>[\0<capabilities>]\n"
        // Determine OID type from capabilities if not yet seen
        if (!state.SeenCapabilities)
        {
            SetOidTypeFromCaps(payload, len, ref state);
        }

        int oidHexSize = GitOid.HexSizeFor(state.OidType);

        if (payload.Length < oidHexSize)
        {
            throw new GitException(GitErrorCode.Error, "error parsing REF pkt-line", GitErrorCategory.Net);
        }

        // C's ref_pkt fails with GIT_ERROR_NET "error parsing REF
        // pkt-line" (smart_pkt.c:335) on a non-hex OID.
        GitOid oid = ParseOidHex(payload[..oidHexSize], state.OidType, "error parsing REF pkt-line");

        // Skip OID + space
        int offset = oidHexSize;
        if (offset >= payload.Length || payload[offset] != (byte)' ')
        {
            throw new GitException(GitErrorCode.Error, "error parsing REF pkt-line", GitErrorCategory.Net);
        }

        offset++;

        // Remaining: name + optional \0 + caps + \n
        ReadOnlySpan<byte> remaining = payload[offset..];

        // C (smart_pkt.c:308-310): "<oid> " with an EMPTY name is rejected ("if (!len) goto out_err").
        if (remaining.Length == 0)
        {
            throw new GitException(GitErrorCode.Error, "error parsing REF pkt-line", GitErrorCategory.Net);
        }

        // Strip trailing newline
        if (remaining.Length > 0 && remaining[^1] == (byte)'\n')
        {
            remaining = remaining[..^1];
        }

        // A name that was only the newline is empty too.
        if (remaining.Length == 0)
        {
            throw new GitException(GitErrorCode.Error, "error parsing REF pkt-line", GitErrorCategory.Net);
        }

        // Check for NUL (capabilities separator)
        int nulIdx = remaining.IndexOf((byte)'\0');
        string name;
        string? caps = null;

        if (nulIdx >= 0)
        {
            name = Encoding.UTF8.GetString(remaining[..nulIdx]);

            if (!state.SeenCapabilities)
            {
                // Capabilities follow the NUL
                caps = Encoding.UTF8.GetString(remaining[(nulIdx + 1)..]);
            }
            else
            {
                // C's ref_pkt (smart_pkt.c:322-327) rejects a
                // caps-bearing ref once capabilities have been seen
                // ("else goto out_err") — a cap-less first ref followed by a
                // caps-bearing ref is an error, not a second caps source.
                throw new GitException(GitErrorCode.Error, "error parsing REF pkt-line", GitErrorCategory.Net);
            }
        }
        else
        {
            name = Encoding.UTF8.GetString(remaining);
        }

        // C's ref_pkt sets data->seen_capabilities = 1 unconditionally
        // at the end of every ref parse (smart_pkt.c:329) — a cap-less first
        // ref still marks capabilities as seen, so any later caps-bearing ref
        // is rejected above.
        state.SeenCapabilities = true;

        var head = new GitRemoteHead(false, oid, default, name, null);
        return new GitRefPacket(head, caps);
    }

    /// <summary>
    /// Extract the OID type from the capabilities in the first ref packet.
    /// Ported from <c>set_data()</c> in <c>smart_pkt.c:224</c>.
    /// </summary>
    private static void SetOidTypeFromCaps(ReadOnlySpan<byte> payload, int _, ref GitPacketParseState state)
    {
        // Find NUL byte after the ref name
        int nulIdx = payload.IndexOf((byte)'\0');
        if (nulIdx < 0 || nulIdx >= payload.Length - 1)
        {
            // No capabilities — default to SHA-1
            if (state.OidType == default)
            {
                state.OidType = GitHashAlgorithmKind.Sha1;
            }

            return;
        }

        // Look for "object-format=" in the caps section
        ReadOnlySpan<byte> caps = payload[(nulIdx + 1)..];
        int ofIdx = FindCapsValue(caps, "object-format="u8);

        if (ofIdx >= 0)
        {
            // Extract the value up to the next space, NUL, or newline
            ReadOnlySpan<byte> val = caps[(ofIdx + "object-format=".Length)..];
            int end = val.IndexOfAny([(byte)' ', (byte)'\0', (byte)'\n']);
            if (end < 0)
            {
                end = val.Length;
            }

            string format = Encoding.ASCII.GetString(val[..end]);

            if (format == "sha1")
            {
                state.OidType = GitHashAlgorithmKind.Sha1;
            }
            else if (format == "sha256")
            {
                state.OidType = GitHashAlgorithmKind.Sha256;
            }
            else
            {
                throw new GitException(GitErrorCode.Error, $"unknown remote object format '{format}'", GitErrorCategory.Invalid);
            }
        }
        else
        {
            if (state.OidType == default)
            {
                state.OidType = GitHashAlgorithmKind.Sha1;
            }
        }
    }

    /// <summary>
    /// Find a capability key in the caps section, handling both leading and
    /// space-delimited positions. Returns the index of the key start,
    /// or -1 if not found.
    /// </summary>
    private static int FindCapsValue(ReadOnlySpan<byte> caps, ReadOnlySpan<byte> key)
    {
        // Check at the start
        if (caps.StartsWith(key))
        {
            return 0;
        }

        // Check after spaces
        byte[] searchKey = new byte[key.Length + 1];
        searchKey[0] = (byte)' ';
        key.CopyTo(searchKey.AsSpan(1));

        int idx = caps.IndexOf(searchKey);
        if (idx >= 0)
        {
            return idx + 1; // skip the space
        }

        return -1;
    }

    private static bool StartsWith(ReadOnlySpan<byte> span, ReadOnlySpan<byte> prefix)
        => span.StartsWith(prefix);

    /// <summary>
    /// Parses an OID from hex packet bytes, mapping <see cref="GitOid.Parse"/>'s
    /// <see cref="FormatException"/> (non-hex or wrong-length content from a
    /// malicious or corrupt server) to the C behavior. ack_pkt/ref_pkt
    /// fail with GIT_ERROR_NET "error parsing ACK/REF pkt-line"
    /// (smart_pkt.c:91,335) — pass the matching <paramref name="errorMessage"/>;
    /// shallow_pkt IGNORES git_oid__fromstr's failure and keeps the ZEROED oid
    /// (smart_pkt.c:478; git_oid__fromstrn zeroes the oid before failing,
    /// oid.c:50) — pass <c>null</c> to return a zeroed OID of the session's
    /// kind instead of throwing.
    /// </summary>
    private static GitOid ParseOidHex(ReadOnlySpan<byte> hex, GitHashAlgorithmKind oidType, string? errorMessage)
    {
        try
        {
            return GitOid.Parse(Encoding.ASCII.GetString(hex), oidType);
        }
        catch (FormatException)
        {
            if (errorMessage is not null)
            {
                throw new GitException(GitErrorCode.Error, errorMessage, GitErrorCategory.Net);
            }

            return GitOid.FromRaw(new byte[GitOid.HexSizeFor(oidType) / 2], oidType);
        }
    }

    private static bool IsHexDigit(char c)
        => c is >= '0' and <= '9' or >= 'a' and <= 'f' or >= 'A' and <= 'F';

    private static int HexValue(byte b)
    {
        if (b is >= ((byte)'0') and <= ((byte)'9'))
        {
            return b - (byte)'0';
        }

        if (b is >= ((byte)'a') and <= ((byte)'f'))
        {
            return b - (byte)'a' + 10;
        }

        if (b is >= ((byte)'A') and <= ((byte)'F'))
        {
            return b - (byte)'A' + 10;
        }

        return 0; // should not reach here — validated by IsHexDigit
    }
}
