using LibGit2CS.Core;
using LibGit2CS.Merge;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Merge;

/// <summary>
/// Golden tests for <see cref="GitRepository.MergeBaseFindAsync"/>, comparing the merge-base
/// OID against <c>git merge-base</c> output captured in
/// <c>Fixtures/merge/expected/merge_base_*.txt</c>.
/// </summary>
/// <remarks>
/// Ported from <c>tests/libgit2/merge/analysis.c</c> (via
/// <c>git_merge_base</c>). The golden files are generated by
/// <c>generate-goldens.sh</c> (merge section) which runs
/// <c>git merge-base</c> on the same branch pairs. Each golden contains
/// a single line: the 40-char merge-base OID.
/// </remarks>
public sealed class MergeBaseGoldenTests : MergeGoldenBase
{
    [Fact]
    public async Task MergeBase_BranchA_MatchesGitMergeBase()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitOid a = await ResolveBranchAsync(repo, "branchA-1");
        GitOid b = await ResolveBranchAsync(repo, "branchA-2");

        GitOid? baseOid = await repo.MergeBaseFindAsync(a, b, CancellationToken.None);
        string expected = LoadExpected("merge_base_branchA").TrimEnd();

        Assert.NotNull(baseOid);
        Assert.Equal(expected, baseOid!.Value.ToString());
    }

    [Fact]
    public async Task MergeBase_BranchF_MatchesGitMergeBase()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitOid a = await ResolveBranchAsync(repo, "branchF-1");
        GitOid b = await ResolveBranchAsync(repo, "branchF-2");

        GitOid? baseOid = await repo.MergeBaseFindAsync(a, b, CancellationToken.None);
        string expected = LoadExpected("merge_base_branchF").TrimEnd();

        Assert.NotNull(baseOid);
        Assert.Equal(expected, baseOid!.Value.ToString());
    }

    [Fact]
    public async Task MergeBase_BranchH_MatchesGitMergeBase()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitOid a = await ResolveBranchAsync(repo, "branchH-1");
        GitOid b = await ResolveBranchAsync(repo, "branchH-2");

        GitOid? baseOid = await repo.MergeBaseFindAsync(a, b, CancellationToken.None);
        string expected = LoadExpected("merge_base_branchH").TrimEnd();

        Assert.NotNull(baseOid);
        Assert.Equal(expected, baseOid!.Value.ToString());
    }
}
