using LibGit2CS.Core;
using LibGit2CS.Objects;
using LibGit2CS.Refs;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Merge;

/// <summary>
/// Shared base for merge golden tests. Handles fixture extraction, repo
/// open, temp-dir cleanup, and branch/tree resolution. Mirrors the
/// <c>IDisposable</c>+temp-dir pattern used by <see cref="MergeRecursiveTests"/>
/// and <see cref="DiffGoldenBase"/>, consolidated for the merge golden corpus.
/// </summary>
/// <remarks>
/// The merge golden fixtures are the existing
/// <c>Fixtures/merge/merge-recursive.zip</c> (packaged by
/// <c>generate-goldens.sh</c> apply section). Expected output files live at
/// <c>Fixtures/merge/expected/merge_*.txt</c> and are generated by the
/// merge section of <c>generate-goldens.sh</c>.
/// </remarks>
public abstract class MergeGoldenBase : IDisposable
{
    private readonly string _tempDir;
    private readonly List<string> _extractedPaths = [];
    private readonly GitContext _context = new();
    protected GitContext Context => _context;

    protected MergeGoldenBase()
    {
        _tempDir = Path.Combine(
            Path.GetTempPath(),
            "LibGit2CS_MergeGolden_" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        _context.Dispose();
        foreach (string path in _extractedPaths)
        {
            try
            {
                Directory.Delete(path, recursive: true);
            }
            catch (IOException) { }
        }

        try
        {
            Directory.Delete(_tempDir, recursive: true);
        }
        catch (IOException) { }
    }

    /// <summary>
    /// Extracts <c>Fixtures/merge/merge-recursive.zip</c> to a temp dir
    /// and opens the repository at the working-tree root. The fixture
    /// contains the merge-recursive test repo with branches branchA-1
    /// through branchK-2 (criss-cross histories, content conflicts, etc.).
    /// </summary>
    protected async ValueTask<GitRepository> OpenMergeRecursiveRepoAsync()
    {
        string extracted = FixtureLoader.ExtractTreeToTemp("Fixtures/merge/merge-recursive.zip");
        _extractedPaths.Add(extracted);
        return await GitRepository.OpenAsync(Path.Combine(extracted, "merge-recursive"), Context);
    }

    /// <summary>
    /// Loads the byte-exact golden output for the given merge case. The
    /// golden files are UTF-8 text (OIDs, ls-files output).
    /// </summary>
    protected static string LoadExpected(string caseName)
        => FixtureLoader.LoadText($"Fixtures/merge/expected/{caseName}.txt");

    /// <summary>
    /// Resolves a branch name to its commit OID. Matches
    /// <c>MergeTestHelpers.ResolveBranch</c> but exposed for golden tests.
    /// </summary>
    protected static async Task<GitOid> ResolveBranchAsync(GitRepository repo, string branchName)
    {
        string refName = branchName.StartsWith(GitReferences.RefsHeadsDir, StringComparison.Ordinal)
            ? branchName
            : GitReferences.RefsHeadsDir + branchName;

        GitReference reference = await repo.ReferenceResolveAsync(refName)
            ?? throw new InvalidOperationException($"branch '{branchName}' not found");

        if (reference is not GitDirectReference direct)
        {
            throw new InvalidOperationException($"branch '{branchName}' is not a direct reference");
        }

        return direct.Target;
    }

    /// <summary>
    /// Resolves a branch name to its <see cref="GitTree"/>. Matches clar's
    /// <c>resolve_commit_oid_to_tree</c> and <see cref="DiffGoldenBase.ResolveTree"/>.
    /// </summary>
    protected static async Task<GitTree> ResolveTreeAsync(GitRepository repo, string branchName)
    {
        GitOid oid = await ResolveBranchAsync(repo, branchName);
        Commit commit = await repo.ObjectLookupAsync<Commit>(oid, TestContext.Current.CancellationToken)
            ?? throw new InvalidOperationException($"commit for branch '{branchName}' not found");
        return await repo.ObjectLookupAsync<GitTree>(commit.Tree, TestContext.Current.CancellationToken)
            ?? throw new InvalidOperationException($"tree for branch '{branchName}' not found");
    }

    /// <summary>
    /// Resolves a branch name to its <see cref="Commit"/>.
    /// </summary>
    protected static async Task<Commit> ResolveCommitAsync(GitRepository repo, string branchName)
    {
        GitOid oid = await ResolveBranchAsync(repo, branchName);
        return await repo.ObjectLookupAsync<Commit>(oid, TestContext.Current.CancellationToken)
            ?? throw new InvalidOperationException($"commit for branch '{branchName}' not found");
    }

    /// <summary>
    /// Reads the raw content of a <c>.git/</c> state file (e.g.
    /// <c>MERGE_HEAD</c>, <c>MERGE_MSG</c>, <c>MERGE_MODE</c>,
    /// <c>ORIG_HEAD</c>). Returns <c>"(missing)"</c> if the file does not
    /// exist.
    /// </summary>
    protected static string ReadStateFile(GitRepository repo, string fileName)
    {
        string path = Path.Combine(repo.Path, fileName);
        if (!File.Exists(path))
        {
            return "(missing)";
        }

        return File.ReadAllText(path);
    }

    /// <summary>
    /// Formats the full merge workdir-state (ORIG_HEAD + MERGE_HEAD +
    /// MERGE_MODE + MERGE_MSG) as a single comparable string with section
    /// headers. Matches the format produced by
    /// <c>generate-goldens.sh</c> (merge-state section).
    /// </summary>
    protected static string FormatMergeState(GitRepository repo)
    {
        var sb = new System.Text.StringBuilder();
        sb.Append("=== ORIG_HEAD ===\n");
        sb.Append(ReadStateFile(repo, "ORIG_HEAD"));
        sb.Append("=== MERGE_HEAD ===\n");
        sb.Append(ReadStateFile(repo, "MERGE_HEAD"));
        sb.Append("=== MERGE_MODE ===\n");
        sb.Append(ReadStateFile(repo, "MERGE_MODE"));
        sb.Append("=== MERGE_MSG ===\n");
        sb.Append(ReadStateFile(repo, "MERGE_MSG"));
        return sb.ToString();
    }
}
