using LibGit2CS.Merge;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Merge;

/// <summary>
/// Golden tests for the merge workdir-state files (<c>MERGE_HEAD</c>,
/// <c>MERGE_MODE</c>, <c>MERGE_MSG</c>, <c>ORIG_HEAD</c>) written by
/// <see cref="GitRepository.MergeAsync"/>. Compares the raw file contents
/// byte-exact against <c>git merge --no-ff --no-commit</c> output captured
/// in <c>Fixtures/merge/expected/merge_state_*.txt</c>.
/// </summary>
/// <remarks>
/// The golden files are generated by <c>generate-goldens.sh</c>
/// (merge-state section) which runs <c>git merge --no-ff
/// --no-commit</c> with pinned dates and concatenates the 4 state files
/// with <c>=== &lt;name&gt; ===</c> section headers.
/// </remarks>
public sealed class MergeStateGoldenTests : MergeGoldenBase
{
    [Fact]
    public async Task MergeState_CleanMerge_MatchesGit()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        await MergeTestHelpers.MergeBranchesAsync(repo, "refs/heads/branchA-1", "refs/heads/branchA-2");

        string actual = FormatMergeState(repo);
        string expected = LoadExpected("merge_state_branchA_clean");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeState_ConflictMerge_MatchesGit()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        await MergeTestHelpers.MergeBranchesAsync(repo, "refs/heads/branchF-1", "refs/heads/branchF-2");

        string actual = FormatMergeState(repo);
        string expected = LoadExpected("merge_state_branchF_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeState_ConflictMerge_CrissCross_MatchesGit()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        await MergeTestHelpers.MergeBranchesAsync(repo, "refs/heads/branchH-1", "refs/heads/branchH-2");

        string actual = FormatMergeState(repo);
        string expected = LoadExpected("merge_state_branchH_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeState_RepositoryState_IsMerge_AfterGitMerge()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        Assert.Equal(RepositoryState.None, repo.State);

        await MergeTestHelpers.MergeBranchesAsync(repo, "refs/heads/branchA-1", "refs/heads/branchA-2");

        Assert.Equal(RepositoryState.Merge, repo.State);
    }
}
