using LibGit2CS.Core;
using LibGit2CS.Merge;
using LibGit2CS.Objects;
using LibGit2CS.Repository;

using GitIndex = LibGit2CS.Index.GitIndex;

namespace LibGit2CS.UnitTests.Merge;

/// <summary>
/// Golden tests for <see cref="GitRepository.MergeTreesAsync"/>, comparing the merged
/// tree OID (clean merges) and conflict entry stages (conflict merges)
/// against reference git output captured in
/// <c>Fixtures/merge/expected/merge_tree_*.txt</c> and
/// <c>Fixtures/merge/expected/merge_tree_stages_*.txt</c>.
/// </summary>
/// <remarks>
/// Ported from <c>tests/libgit2/merge/trees/recursive.c</c> (via
/// <c>git_merge_trees</c>). The golden files are generated by
/// <c>generate-goldens.sh</c> (merge section).
///
/// <b>Tree-level vs commit-level.</b> <see cref="GitRepository.MergeTreesAsync"/>
/// performs a three-way merge with a single explicit base (from
/// <see cref="GitRepository.MergeBaseFindAsync"/>). The goldens use
/// <c>git merge-tree --write-tree --merge-base=&lt;base&gt;</c> with the
/// same single base, and <c>git read-tree -m &lt;base&gt; &lt;ours&gt;
/// &lt;theirs&gt;</c> + <c>git ls-files -s</c> for conflict stages. This
/// makes the comparison fair — both C# and git use the same single base.
/// Criss-cross histories (branchB, branchC) conflict with a single base
/// but merge clean with recursive merge (see
/// <see cref="MergeCommitsGoldenTests"/>).
/// </remarks>
public sealed class MergeTreesGoldenTests : MergeGoldenBase
{
    /// <summary>
    /// Performs a three-way tree merge of two branches using
    /// <see cref="GitRepository.MergeBaseFindAsync"/> to compute the merge base, then
    /// <see cref="GitRepository.MergeTreesAsync"/> to merge. Returns the resulting
    /// index. Mirrors <c>MergeTestHelpers.MergeTreesFromBranches</c> but
    /// without the assertion helpers.
    /// </summary>
    private static async Task<GitIndex> MergeTreesFromBranchesAsync(GitRepository repo, string oursName, string theirsName)
    {
        GitOid ourOid = await ResolveBranchAsync(repo, oursName);
        GitOid theirOid = await ResolveBranchAsync(repo, theirsName);

        Commit? ourCommit = await repo.ObjectLookupAsync<Commit>(ourOid, TestContext.Current.CancellationToken);
        Assert.NotNull(ourCommit);
        Commit? theirCommit = await repo.ObjectLookupAsync<Commit>(theirOid, TestContext.Current.CancellationToken);
        Assert.NotNull(theirCommit);

        GitOid? baseOid = await repo.MergeBaseFindAsync(ourOid, theirOid, TestContext.Current.CancellationToken);
        GitTree? ancestorTree = null;
        if (baseOid is { } baseId)
        {
            Commit? baseCommit = await repo.ObjectLookupAsync<Commit>(baseId, TestContext.Current.CancellationToken);
            Assert.NotNull(baseCommit);
            ancestorTree = await repo.ObjectLookupAsync<GitTree>(baseCommit.Tree, TestContext.Current.CancellationToken);
        }

        GitTree? ourTree = await repo.ObjectLookupAsync<GitTree>(ourCommit.Tree, TestContext.Current.CancellationToken);
        Assert.NotNull(ourTree);
        GitTree? theirTree = await repo.ObjectLookupAsync<GitTree>(theirCommit.Tree, TestContext.Current.CancellationToken);
        Assert.NotNull(theirTree);

        return await repo.MergeTreesAsync(ancestorTree, ourTree, theirTree);
    }

    [Fact]
    public async Task MergeTrees_BranchA_Clean_MatchesGitMergeTree()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchA-1", "branchA-2");

        // Clean merge: the merged tree OID should match the golden.
        // The golden file contains the tree OID from `git merge-tree
        // --write-tree --merge-base=<base>`. We write the merged index
        // to a tree and compare.
        GitOid mergedTreeOid = await index.WriteTreeToAsync(repo, cancellationToken: TestContext.Current.CancellationToken);
        string expected = LoadExpected("merge_tree_branchA_clean").TrimEnd();

        Assert.Equal(expected, mergedTreeOid.ToString());
    }

    [Fact]
    public async Task MergeTrees_BranchB_Conflict_MatchesGitReadTreeStages()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchB-1", "branchB-2");

        // branchB conflicts with a single base (criss-cross: 2 bases).
        // Compare the full index (including conflict stages) against the
        // tree-stages golden from `git read-tree -m <base> <ours> <theirs>`.
        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_tree_stages_branchB_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeTrees_BranchC_Conflict_MatchesGitReadTreeStages()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchC-1", "branchC-2");

        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_tree_stages_branchC_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeTrees_BranchF_Conflict_MatchesGitReadTreeStages()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchF-1", "branchF-2");

        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_tree_stages_branchF_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeTrees_BranchH_Conflict_MatchesGitReadTreeStages()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchH-1", "branchH-2");

        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_tree_stages_branchH_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeTrees_BranchJ_Conflict_MatchesGitReadTreeStages()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        GitIndex index = await MergeTreesFromBranchesAsync(repo, "branchJ-1", "branchJ-2");

        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_tree_stages_branchJ_conflict");

        Assert.Equal(expected, actual);
    }
}
