using LibGit2CS.Merge;
using LibGit2CS.Objects;
using LibGit2CS.Repository;

using GitIndex = LibGit2CS.Index.GitIndex;

namespace LibGit2CS.UnitTests.Merge;

/// <summary>
/// Golden tests for <see cref="GitRepository.MergeCommitsAsync"/>, comparing the
/// merged index (entry-for-entry, including conflict stages) against
/// <c>git ls-files -s</c> output captured in
/// <c>Fixtures/merge/expected/merge_commit_*.txt</c>.
/// </summary>
/// <remarks>
/// Ported from <c>tests/libgit2/merge/workdir/simple.c</c> (via
/// <c>git_merge_commits</c>). The golden files are generated by
/// <c>generate-goldens.sh</c> (merge section) which runs
/// <c>git merge --no-ff --no-commit</c> with pinned dates, then
/// <c>git ls-files -s</c> to capture the full index state including
/// conflict stages (0=merged, 1=base, 2=ours, 3=theirs).
/// </remarks>
public sealed class MergeCommitsGoldenTests : MergeGoldenBase
{
    [Fact]
    public async Task MergeCommits_BranchA_Clean_MatchesGitLsFiles()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        Commit ourCommit = await ResolveCommitAsync(repo, "branchA-1");
        Commit theirCommit = await ResolveCommitAsync(repo, "branchA-2");

        GitIndex index = await repo.MergeCommitsAsync(ourCommit, theirCommit, cancellationToken: TestContext.Current.CancellationToken);
        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_commit_branchA_clean");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeCommits_BranchC_Clean_Recursive_MatchesGitLsFiles()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        Commit ourCommit = await ResolveCommitAsync(repo, "branchC-1");
        Commit theirCommit = await ResolveCommitAsync(repo, "branchC-2");

        // branchC is a criss-cross merge: two merge bases. The recursive
        // merge (GitRepository.MergeCommitsAsync) computes a virtual base and
        // merges clean. The tree-level merge (GitRepository.MergeTreesAsync
        // with a single base) conflicts — see MergeTreesGoldenTests for that
        // distinction.
        GitIndex index = await repo.MergeCommitsAsync(ourCommit, theirCommit, cancellationToken: TestContext.Current.CancellationToken);
        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_commit_branchC_clean");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeCommits_BranchF_Conflict_MatchesGitLsFiles()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        Commit ourCommit = await ResolveCommitAsync(repo, "branchF-1");
        Commit theirCommit = await ResolveCommitAsync(repo, "branchF-2");

        GitIndex index = await repo.MergeCommitsAsync(ourCommit, theirCommit, cancellationToken: TestContext.Current.CancellationToken);
        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_commit_branchF_conflict");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task MergeCommits_BranchH_Conflict_MatchesGitLsFiles()
    {
        await using GitRepository repo = await OpenMergeRecursiveRepoAsync();
        Commit ourCommit = await ResolveCommitAsync(repo, "branchH-1");
        Commit theirCommit = await ResolveCommitAsync(repo, "branchH-2");

        GitIndex index = await repo.MergeCommitsAsync(ourCommit, theirCommit, cancellationToken: TestContext.Current.CancellationToken);
        string actual = IndexGoldenFormatter.FormatLsFiles(index);
        string expected = LoadExpected("merge_commit_branchH_conflict");

        Assert.Equal(expected, actual);
    }
}
