using LibGit2CS.Index;
using LibGit2CS.Objects;
using LibGit2CS.Repository;
using LibGit2CS.Submodule;

using SubmoduleApi = LibGit2CS.Submodule.GitSubmodule;

namespace LibGit2CS.UnitTests.Submodule;

/// <summary>
/// Golden tests for <see cref="SubmoduleApi.ForEachAsync"/> and
/// <see cref="SubmoduleApi.StatusAsync"/>, comparing the C# submodule enumeration
/// and status output byte-exact against <c>git submodule status</c> captured
/// in <c>Fixtures/submodule/expected/submodule_*.txt</c>.
/// </summary>
/// <remarks>
/// The golden files are generated by <c>generate-goldens.sh</c>
/// (submodule section) which packages the libgit2
/// <c>submodule_simple</c> fixture and runs <c>git submodule status</c>.
/// The fixture has one submodule gitlink (<c>testrepo</c>) that is not
/// initialized — git reports <c>-</c> prefix, C# reports
/// <see cref="SubmoduleStatus.WdUninitialized"/>.
/// </remarks>
public sealed class SubmoduleGoldenTests : SubmoduleGoldenBase
{
    [Fact]
    public async Task ForEach_EnumeratesSubmodule_MatchesGitSubmoduleStatus()
    {
        await using GitRepository repo = await OpenSubmoduleRepo();
        var submodules = new List<SubmoduleApi>();
        await foreach (SubmoduleApi e in SubmoduleApi.ForEachAsync(repo, cancellationToken: TestContext.Current.CancellationToken))
        {
            submodules.Add(e);
        }
        string actual = SubmoduleGoldenFormatter.FormatStatus(submodules);
        string expected = LoadExpected("submodule_status_simple");

        Assert.Equal(expected, actual);
    }

    [Fact]
    public async Task Status_NotInitialized_NotInWorkdir()
    {
        await using GitRepository repo = await OpenSubmoduleRepo();
        SubmoduleStatus status = await SubmoduleApi.StatusAsync(repo, "testrepo", cancellationToken: TestContext.Current.CancellationToken);

        // The submodule is in HEAD + index + config but not in the workdir
        // (the testrepo/ directory doesn't exist in the fixture). Git reports
        // this as '-' (not initialized).
        Assert.True((status & SubmoduleStatus.InHead) != 0);
        Assert.True((status & SubmoduleStatus.InIndex) != 0);
        Assert.True((status & SubmoduleStatus.InConfig) != 0);
        Assert.True((status & SubmoduleStatus.InWd) == 0);
    }

    [Fact]
    public async Task Lookup_ReturnsSubmoduleWithCorrectProperties()
    {
        await using GitRepository repo = await OpenSubmoduleRepo();
        SubmoduleApi? sm = await SubmoduleApi.LookupAsync(repo, "testrepo", cancellationToken: TestContext.Current.CancellationToken);

        Assert.NotNull(sm);
        Assert.Equal("testrepo", sm!.Name);
        Assert.Equal("testrepo", sm.Path?.ToUtf8String());
        Assert.NotEmpty(sm.Url ?? "");
    }

    [Fact]
    public async Task ForEach_EmptyRepo_ReturnsEmpty_MatchesGit()
    {
        await using GitRepository repo = await OpenNoSubmoduleRepo();
        var submodules = new List<SubmoduleApi>();
        await foreach (SubmoduleApi e in SubmoduleApi.ForEachAsync(repo, cancellationToken: TestContext.Current.CancellationToken))
        {
            submodules.Add(e);
        }

        Assert.Empty(submodules);
    }

    [Fact]
    public async Task ForEach_StatusFormat_MatchesGitExactly()
    {
        // Verify the exact format: "-<oid> <name>\n" with no description
        // (because the submodule is not initialized).
        await using GitRepository repo = await OpenSubmoduleRepo();
        var submodules = new List<SubmoduleApi>();
        await foreach (SubmoduleApi e in SubmoduleApi.ForEachAsync(repo, cancellationToken: TestContext.Current.CancellationToken))
        {
            submodules.Add(e);
        }
        string actual = SubmoduleGoldenFormatter.FormatStatus(submodules);

        // The golden file contains exactly:
        // "-be3563ae3f795b2b4353bcce3a527ad0a4f7f644 testrepo\n"
        Assert.StartsWith("-be3563ae", actual);
        Assert.Contains(" testrepo\n", actual);
    }

    [Fact]
    public async Task Index_ContainsGitlinkEntry_MatchesGit()
    {
        await using GitRepository repo = await OpenSubmoduleRepo();
        GitIndexEntry entry = (await repo.GetIndexAsync(cancellationToken: TestContext.Current.CancellationToken)).Entries.FirstOrDefault(e => e.Path.ToUtf8String() == "testrepo");

        Assert.Equal(GitFileMode.GitLink, entry.Mode);
        Assert.Equal("be3563ae3f795b2b4353bcce3a527ad0a4f7f644", entry.Id.ToString());
    }
}
