using LibGit2CS.Core;
using LibGit2CS.Repository;

namespace LibGit2CS.UnitTests.Submodule;

/// <summary>
/// Shared base for submodule golden tests. Handles fixture extraction,
/// repo open, temp-dir cleanup, and golden file loading. Mirrors the
/// <see cref="IDisposable"/>+temp-dir pattern used by
/// <see cref="Merge.MergeGoldenBase"/>.
/// </summary>
/// <remarks>
/// The submodule golden fixture is <c>Fixtures/submodule/submodule_simple.zip</c>
/// (packaged from libgit2's <c>tests/resources/submodule_simple</c>). Expected
/// output files live at <c>Fixtures/submodule/expected/submodule_*.txt</c>
/// and are generated by the submodule section of
/// <c>generate-goldens.sh</c>.
/// </remarks>
public abstract class SubmoduleGoldenBase : IDisposable
{
    private readonly string _tempDir;
    private readonly List<string> _extractedPaths = [];
    private readonly GitContext _context = new();
    protected GitContext Context => _context;

    protected SubmoduleGoldenBase()
    {
        _tempDir = Path.Combine(
            Path.GetTempPath(),
            "LibGit2CS_SubmoduleGolden_" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        _context.Dispose();
        foreach (string path in _extractedPaths)
        {
            try
            {
                Directory.Delete(path, recursive: true);
            }
            catch (IOException) { }
        }

        try
        {
            Directory.Delete(_tempDir, recursive: true);
        }
        catch (IOException) { }
    }

    /// <summary>
    /// Extracts <c>Fixtures/submodule/submodule_simple.zip</c> to a temp dir
    /// and opens the repository at the working-tree root. The fixture is a
    /// superproject with one submodule gitlink (<c>testrepo</c>) that is not
    /// initialized (the submodule's <c>.git</c> points to a non-existent
    /// <c>.git/modules/testrepo</c>).
    /// </summary>
    protected async ValueTask<GitRepository> OpenSubmoduleRepo()
    {
        string extracted = FixtureLoader.ExtractTreeToTemp("Fixtures/submodule/submodule_simple.zip");
        _extractedPaths.Add(extracted);
        return await GitRepository.OpenAsync(Path.Combine(extracted, "submodule_simple"), Context);
    }

    /// <summary>
    /// Extracts <c>Fixtures/blame/testrepo.zip</c> (a non-bare repo with no
    /// submodules) for the empty-submodule-set test case.
    /// </summary>
    protected async ValueTask<GitRepository> OpenNoSubmoduleRepo()
    {
        string extracted = FixtureLoader.ExtractTreeToTemp("Fixtures/blame/testrepo.zip");
        _extractedPaths.Add(extracted);
        return await GitRepository.OpenAsync(Path.Combine(extracted, "testrepo"), Context);
    }

    /// <summary>
    /// Loads the byte-exact golden output for the given submodule case.
    /// </summary>
    protected static string LoadExpected(string caseName)
        => FixtureLoader.LoadText($"Fixtures/submodule/expected/{caseName}.txt");
}
