using System.Text;

using LibGit2CS.Submodule;

namespace LibGit2CS.UnitTests.Submodule;

/// <summary>
/// Serializes submodule state to text formats compatible with reference
/// <c>git</c> commands, so that submodule golden tests can compare C# output
/// byte-exact against golden files generated by
/// <c>generate-goldens.sh</c> (submodule section).
/// </summary>
internal static class SubmoduleGoldenFormatter
{
    /// <summary>
    /// Formats the submodule status as <c>git submodule status</c> output.
    /// Each line: <c>&lt;flag&gt;&lt;oid&gt; &lt;name&gt; (&lt;desc&gt;)</c>
    /// where flag is a single character:
    /// <list type="bullet">
    /// <item><c>' '</c> (space) — unmodified</item>
    /// <item><c>'-'</c> — not initialized (WdUninitialized)</item>
    /// <item><c>'+'</c> — workdir HEAD differs from index (WdModified)</item>
    /// <item><c>'U'</c> — merge conflict</item>
    /// <item><c>'?'</c> — untracked</item>
    /// </list>
    /// The description in parentheses is omitted when the submodule is not
    /// initialized (matching git's behavior for the <c>-</c> flag).
    /// </summary>
    public static string FormatStatus(IReadOnlyList<GitSubmodule> submodules)
    {
        ArgumentNullException.ThrowIfNull(submodules);

        var sb = new StringBuilder();
        foreach (GitSubmodule sm in submodules)
        {
            char flag = StatusFlag(sm.StatusFlags);
            sb.Append(flag);
            sb.Append(sm.IndexId.IsZero ? sm.HeadId : sm.IndexId);
            sb.Append(' ');
            sb.Append(sm.Name);

            // Description in parentheses — only when initialized and
            // the HEAD is resolvable. For uninitialized submodules (the
            // `-` flag), git omits the description.
            if (flag != '-' && !sm.WdId.IsZero)
            {
                sb.Append(" (");
                sb.Append(sm.WdId);
                sb.Append(')');
            }

            sb.Append('\n');
        }

        return sb.ToString();
    }

    /// <summary>
    /// Maps <see cref="SubmoduleStatus"/> flags to the single-character
    /// prefix used by <c>git submodule status</c>. Matches the precedence
    /// in git's <c>print_status</c> (builtin/submodule--helper.c):
    /// not-in-workdir → '-', modified → '+', untracked → '?', else ' '.
    /// The '-' prefix covers both "directory missing" and "directory exists
    /// but repo not initialized" — git reports both as "not initialized".
    /// </summary>
    private static char StatusFlag(SubmoduleStatus status)
    {
        // Not in workdir (directory missing or repo not initialized).
        if ((status & SubmoduleStatus.InWd) == 0)
        {
            return '-';
        }

        if ((status & SubmoduleStatus.WdUninitialized) != 0)
        {
            return '-';
        }

        if ((status & (SubmoduleStatus.WdModified | SubmoduleStatus.WdAdded)) != 0)
        {
            return '+';
        }

        return ' ';
    }
}
