using System.Text;

using LibGit2CS.Repository;

using GitBlame = LibGit2CS.Blame.GitBlame;

namespace LibGit2CS.UnitTests.Blame;

/// <summary>
/// Buffer blame tests ported from libgit2's <c>tests/libgit2/blame/buffer.c</c>.
/// Each test creates a file blame for <c>b.txt</c> in <c>blametest.git</c>,
/// then calls <see cref="Blame.Buffer"/> with modified content and asserts
/// the resulting hunks.
/// </summary>
public sealed class BufferBlameTests : BlameGoldenBase, IAsyncDisposable
{
    private async Task<GitBlame> CreateFileBlameAsync()
    {
        GitRepository repo = await OpenBareFixtureRepoAsync("blametest.git");
        GitBlame blame = await repo.BlameFileAsync("b.txt");
        // Keep repo alive for the test duration — store it in a field
        _repoRef = repo;
        return blame;
    }

    private GitRepository? _repoRef;

    // buffer.c::4_edits
    [Fact]
    public async Task FourEdits()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nxEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nx\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nxBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nxBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(10, bufBlame.HunkCount);
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 2, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 3, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 4, 1, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 5, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 6, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 5, 7, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 6, 8, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 7, 9, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 8, 10, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 9, 11, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::two_added_lines_and_one_modified
    [Fact]
    public async Task TwoAddedLinesAndOneModified()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nx\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nx\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nxBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(8, bufBlame.HunkCount);
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 3, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 4, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 5, 1, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 6, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 7, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 5, 8, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 6, 9, 3, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 7, 12, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::two_added_lines
    [Fact]
    public async Task TwoAddedLines()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nabc\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\ndef\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 3, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 4, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 5, 1, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 6, 1, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 7, 5, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 5, 12, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::added_blocks
    [Fact]
    public async Task AddedBlocks()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nabcdefg\nhijlmno\npqrstuv\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nabcdefg\nhijlmno\npqrstuv\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\nabcdefg\nhijlmno\npqrstuv\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 4, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 5, 1, 1, "b99f7ac0", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 3, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 9, 4, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 13, 3, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 5, 16, 5, 0, "aa06ecca", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 6, 21, 3, 0, "000000", "b.txt");
    }

    // buffer.c::overlapping_blocks
    [Fact]
    public async Task OverlappingBlocks()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nabcdefg\nhijlmno\npqrstuv\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 3, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 4, 3, 0, "000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 7, 4, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 11, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::2_add_splits_hunk
    [Fact]
    public async Task TwoAddSplitsHunk()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nabc\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nabc\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 2, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 3, 1, 0, "00000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 4, 2, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 6, 1, 1, "b99f7ac0", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 7, 2, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 5, 9, 1, 0, "00000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 6, 10, 3, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 7, 13, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::deleted_line
    [Fact]
    public async Task DeletedLine()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 3, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 9, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 10, 5, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::add_splits_hunk
    [Fact]
    public async Task AddSplitsHunk()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nabc\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 2, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 8, 1, 0, "00000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 9, 3, 0, "63d671eb", "b.txt");
    }

    // buffer.c::delete_crosses_hunk_boundary
    [Fact]
    public async Task DeleteCrossesHunkBoundary()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 7, 2, 0, "aa06ecca", "b.txt");
    }

    // buffer.c::replace_line
    [Fact]
    public async Task ReplaceLine()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nabc\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 1, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 7, 1, 0, "00000000", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 8, 3, 0, "63d671eb", "b.txt");
    }

    // buffer.c::add_lines_at_end
    [Fact]
    public async Task AddLinesAtEnd()
    {
        using GitBlame fileBlame = await CreateFileBlameAsync();
        string buffer = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n\nabc\ndef\n";
        using GitBlame bufBlame = await GitBlame.BufferAsync(fileBlame, Encoding.UTF8.GetBytes(buffer), cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal(5, bufBlame.HunkCount);
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 0, 1, 4, 0, "da237394", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 1, 5, 1, 1, "b99f7ac0", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 2, 6, 5, 0, "63d671eb", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 3, 11, 5, 0, "aa06ecca", "b.txt");
        await BlameHunkVerifier.AssertHunkAsync(_repoRef!, bufBlame, 4, 16, 2, 0, "00000000", "b.txt");
    }

    public async ValueTask DisposeAsync()
    {
        if (_repoRef is not null)
        {
            await _repoRef.DisposeAsync();
        }
    }
}
