namespace LibGit2CS.UnitTests.Message;

/// <summary>
/// Shared base for message/trailer golden tests. Provides
/// <see cref="LoadExpected"/> for loading byte-exact golden output from
/// <c>Fixtures/message/expected/&lt;case&gt;.txt</c> (generated by
/// <c>generate-goldens.sh</c> via <c>git stripspace</c> and
/// <c>git interpret-trailers --parse</c>).
/// </summary>
/// <remarks>
/// Message/trailer goldens are pure string I/O — no repo fixture, no
/// <c>IDisposable</c> temp-dir management needed. The expected files are
/// embedded via the <c>Fixtures\**\*</c> glob in the test csproj and
/// loaded at runtime via <see cref="FixtureLoader.LoadText"/>.
/// </remarks>
public abstract class MessageGoldenBase
{
    /// <summary>
    /// Loads the byte-exact golden output for the given case. The golden
    /// files are UTF-8 text (commit messages and trailer blocks contain
    /// only ASCII in the test corpus).
    /// </summary>
    protected static string LoadExpected(string caseName)
        => FixtureLoader.LoadText($"Fixtures/message/expected/{caseName}.txt");
}
