using Msg = LibGit2CS.Core.GitMessage;

namespace LibGit2CS.UnitTests.Message;

/// <summary>
/// Golden tests for <see cref="Msg.Prettify"/>, comparing byte-exact
/// output against <c>git stripspace</c> / <c>git stripspace -s</c> output
/// captured in <c>Fixtures/message/expected/prettify_*.txt</c>.
/// </summary>
/// <remarks>
/// Ported from <c>tests/libgit2/message/prettify.c</c> (via
/// <c>git_message_prettify</c>). The golden files are generated by
/// <c>generate-goldens.sh</c> (message section) which pipes the same
/// inputs through <c>git stripspace</c>. This catches byte-level
/// regressions in whitespace stripping, blank-line collapse, and comment
/// removal that the unit tests in <see cref="MessageTests"/> might miss.
/// </remarks>
public sealed class MessageGoldenTests : MessageGoldenBase
{
    [Fact]
    public void Prettify_CleanMessage_MatchesGitStripspace()
    {
        string input = "Subject line\n\nBody paragraph here.\n";
        string result = Msg.Prettify(input, '#');
        Assert.Equal(LoadExpected("prettify_clean"), result);
    }

    [Fact]
    public void Prettify_TrailingWhitespace_MatchesGitStripspace()
    {
        string input = "hello   \n\n\nworld\n\n";
        string result = Msg.Prettify(input, '#');
        Assert.Equal(LoadExpected("prettify_trailing_ws"), result);
    }

    [Fact]
    public void Prettify_CollapseBlankLines_MatchesGitStripspace()
    {
        string input = "first\n\n\n\nsecond\n";
        string result = Msg.Prettify(input, '#');
        Assert.Equal(LoadExpected("prettify_collapse_blanks"), result);
    }

    [Fact]
    public void Prettify_StripComments_MatchesGitStripspace()
    {
        string input = "subject\n\nbody\n# this is a comment\nmore body\n# another comment\n";
        string result = Msg.Prettify(input, '#', stripComments: true);
        Assert.Equal(LoadExpected("prettify_strip_comments"), result);
    }

    [Fact]
    public void Prettify_OnlyBlankLines_MatchesGitStripspace()
    {
        string input = "\n\n\n";
        string result = Msg.Prettify(input, '#');
        Assert.Equal(LoadExpected("prettify_only_blanks"), result);
    }
}
