using LibGit2CS.Core;

namespace LibGit2CS.UnitTests.Message;

/// <summary>
/// Golden tests for <see cref="GitTrailers.Parse"/>, comparing byte-exact
/// output against <c>git interpret-trailers --parse</c> output captured
/// in <c>Fixtures/message/expected/trailers_*.txt</c>.
/// </summary>
/// <remarks>
/// Ported from <c>tests/libgit2/message/trailer.c</c> (via
/// <c>git_message_trailers</c>). The golden files are generated by
/// <c>generate-goldens.sh</c> (message section) which pipes the same
/// inputs through <c>git interpret-trailers --parse</c>. The C# test
/// serializes the parsed <see cref="GitMessageTrailer"/> list to the same
/// <c>Key: Value</c> format for byte-exact comparison.
/// </remarks>
public sealed class TrailerGoldenTests : MessageGoldenBase
{
    /// <summary>
    /// Serializes parsed trailers to the <c>git interpret-trailers --parse</c>
    /// output format: one <c>Key: Value</c> line per trailer, with a trailing
    /// newline. Matches the golden file format.
    /// </summary>
    private static string FormatTrailers(IReadOnlyList<GitMessageTrailer> trailers)
    {
        var sb = new System.Text.StringBuilder();
        foreach (GitMessageTrailer t in trailers)
        {
            sb.Append(t.Key).Append(": ").Append(t.Value).Append('\n');
        }

        return sb.ToString();
    }

    [Fact]
    public void Trailers_Simple_MatchesGitInterpretTrailers()
    {
        string input = "Message\n\nSigned-off-by: foo@bar.com\nSigned-off-by: someone@else.com\n";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_simple"), result);
    }

    [Fact]
    public void Trailers_NoWhitespace_MatchesGitInterpretTrailers()
    {
        string input = "Message\n\nKey:value\n";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_no_whitespace"), result);
    }

    [Fact]
    public void Trailers_ExtraWhitespace_MatchesGitInterpretTrailers()
    {
        string input = "Message\n\nKey   :   value\n";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_extra_whitespace"), result);
    }

    [Fact]
    public void Trailers_NoNewline_MatchesGitInterpretTrailers()
    {
        string input = "Message\n\nKey: value";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_no_newline"), result);
    }

    [Fact]
    public void Trailers_NotLastParagraph_MatchesGitInterpretTrailers()
    {
        string input = "Message\n\nKey: value\n\nMore stuff\n";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_not_last_paragraph"), result);
    }

    [Fact]
    public void Trailers_MultipleTypes_MatchesGitInterpretTrailers()
    {
        string input = "Fix a bug\n\nThis fixes the issue reported in #42.\n\nSigned-off-by: Alice <alice@example.com>\nReviewed-by: Bob <bob@example.com>\nAcked-by: Carol <carol@example.com>\n";
        string result = FormatTrailers(GitTrailers.Parse(input));
        Assert.Equal(LoadExpected("trailers_multiple_types"), result);
    }
}
