namespace LibGit2CS.IntegrationTests.DockerFixture;

/// <summary>
/// Static facade for git-over-SSH Docker test fixtures: exposes the
/// in-container constants (<see cref="TestUser"/>, <see cref="TestPassword"/>,
/// <see cref="Host"/>, <see cref="RepoPath"/>) and the Docker-reachability
/// gate (<see cref="SkipIfDockerNotAvailable"/>). The build-vs-run split lives
/// in <see cref="SshGitImageFixtureBase"/> (one built image per variant, shared
/// across tests via its subclass assembly fixtures) and
/// <see cref="SshGitDockerContainer"/> (a fresh per-test container started
/// from a pre-built image).
/// </summary>
/// <remarks>
/// <para>
/// <b>Architecture.</b> Splitting image build (expensive: apt/apk install,
/// ssh-keygen, user creation, repo seed) from container start (cheap: forks
/// a new sshd from the image) lets the assembly fixture prepare each image
/// variant on first use and reuse it across runs. Each
/// test gets a fresh container with the clean seeded repo (one commit
/// on <c>refs/heads/main</c>), so tests that mutate server state via
/// <see cref="SshGitDockerContainer.ExecAsync"/> don't affect each other.
/// </para>
/// <para>
/// <b>Auth methods covered.</b> Password + publickey (file + memory) + agent
/// are exercised end-to-end against the default Alpine image. Keyboard-
/// interactive requires a PAM-linked sshd (Alpine's <c>openssh-server</c> is
/// built without libpam and ignores <c>KbdInteractiveAuthentication yes</c>),
/// so the kbdint test uses the Debian variant. Kbdint dispatch is also
/// exercised at the unit-test level via <c>SshTransportAuthTests</c>
/// (fake-backed <c>ISshSession</c>).
/// </para>
/// <para>
/// <b>Gating.</b> <see cref="ShouldRun"/> gates the tests — they no-op when
/// Docker is not reachable (socket on Unix, named pipe on Windows).
/// <see cref="SshGitImageFixtureBase.StartContainerAsync"/> calls
/// <see cref="SkipIfDockerNotAvailable"/> internally, so tests don't need
/// their own skip call.
/// </para>
/// <para>
/// <b>Container host keys</b> are generated by <c>ssh-keygen -A</c> at
/// image build time and shared by containers using that cached image. Known_hosts tests use
/// <see cref="SshGitDockerContainer.GetHostKeyAsync"/> to fetch the real key
/// at runtime.
/// </para>
/// </remarks>
internal static class SshGitDockerFixture
{
    /// <summary>The test user created in the container.</summary>
    public const string TestUser = "testuser";

    /// <summary>The test user's password.</summary>
    public const string TestPassword = "testpass";

    /// <summary>Container host as seen from the test process (always loopback).</summary>
    public const string Host = "127.0.0.1";

    /// <summary>Path inside the container to the seeded non-bare test repo.</summary>
    public const string RepoPath = "/home/testuser/repo.git";

    /// <summary>
    /// True iff Docker appears reachable (socket on Unix, named pipe on
    /// Windows).
    /// </summary>
    public static bool ShouldRun()
    {
        return File.Exists("/var/run/docker.sock")
            || (OperatingSystem.IsWindows() && Directory.Exists(@"\\.\pipe\docker_engine"));
    }

    /// <summary>
    /// Skips the current test when Docker is not reachable. Called internally
    /// by <see cref="SshGitImageFixtureBase.StartContainerAsync"/>; tests do
    /// not need to call this themselves.
    /// </summary>
    public static void SkipIfDockerNotAvailable()
    {
        if (!ShouldRun())
        {
            Assert.Skip("Docker not reachable; skipping test.");
        }
    }
}
