using LibGit2CS.Core;
using LibGit2CS.Objects;
using LibGit2CS.Repository;
using LibGit2CS.UnitTests.Merge;

using GitCheckoutOptions = LibGit2CS.Checkout.GitCheckoutOptions;
using GitCheckoutStrategy = LibGit2CS.Checkout.GitCheckoutStrategy;

namespace LibGit2CS.UnitTests.Checkout;

/// <summary>
/// Golden tests for <see cref="GitRepository.CheckoutTreeAsync"/>, comparing the
/// C# checkout workdir state + index state byte-exact against reference
/// <c>git checkout</c> captured in
/// <c>Fixtures/checkout/expected/checkout_*.txt</c>.
/// </summary>
/// <remarks>
/// The golden files are generated by <c>generate-goldens.sh</c>
/// (checkout section) which builds a repo with 2 commits, checks
/// out the target tree, and captures both <c>git ls-files -s</c> (index)
/// and a workdir file snapshot (path + SHA-1 + size).
/// </remarks>
public sealed class CheckoutGoldenTests : CheckoutGoldenBase
{
    [Fact]
    public async Task CheckoutTree_Clean_MatchesGit()
    {
        await using GitRepository repo = await CreateRepo();
        GitTree headTree = await ResolveHeadTreeAsync(repo);

        await repo.CheckoutTreeAsync(headTree, new GitCheckoutOptions
        {
            Strategy = GitCheckoutStrategy.Force,
        }, cancellationToken: TestContext.Current.CancellationToken);

        await AssertIndexAndWorkdir(repo, "clean");
    }

    [Fact]
    public async Task CheckoutTree_ForceWithUntracked_MatchesGit()
    {
        await using GitRepository repo = await CreateRepo();
        GitTree headTree = await ResolveHeadTreeAsync(repo);

        // Add an untracked file to verify Force overwrites it.
        await File.WriteAllTextAsync(Path.Combine(repo.Workdir!, "dir1", "untracked.txt"), "untracked\n", cancellationToken: TestContext.Current.CancellationToken);

        await repo.CheckoutTreeAsync(headTree, new GitCheckoutOptions
        {
            Strategy = GitCheckoutStrategy.Force,
        }, cancellationToken: TestContext.Current.CancellationToken);

        await AssertIndexAndWorkdir(repo, "force_untracked");
    }

    [Fact]
    public async Task CheckoutTree_SpecificTree_MatchesGit()
    {
        await using GitRepository repo = await CreateRepo();
        GitOid firstCommit = await ResolveFirstCommitOidAsync(repo);
        GitTree? firstTree = await repo.ObjectLookupAsync<GitTree>((await repo.ObjectLookupAsync<Commit>(firstCommit, TestContext.Current.CancellationToken))!.Tree, TestContext.Current.CancellationToken);

        await repo.CheckoutTreeAsync(firstTree, new GitCheckoutOptions
        {
            Strategy = GitCheckoutStrategy.Force,
        }, cancellationToken: TestContext.Current.CancellationToken);

        await AssertIndexAndWorkdir(repo, "tree_head1");
    }

    private static async Task AssertIndexAndWorkdir(GitRepository repo, string caseName)
    {
        LibGit2CS.Index.GitIndex idx = await repo.GetIndexAsync();
        // Index comparison via IndexGoldenFormatter.
        string actualIndex = IndexGoldenFormatter.FormatLsFiles(idx);
        string expectedIndex = LoadExpected($"checkout_index_{caseName}");
        Assert.Equal(expectedIndex, actualIndex);

        // Workdir comparison via CheckoutGoldenFormatter.
        var trackedPaths = idx.Entries.Select(e => e.Path.ToUtf8String()).ToList();
        string actualWorkdir = CheckoutGoldenFormatter.FormatWorkdirSnapshot(repo.Workdir!, trackedPaths);
        string expectedWorkdir = LoadExpected($"checkout_workdir_{caseName}");
        Assert.Equal(expectedWorkdir, actualWorkdir);
    }

    private static async Task<GitTree> ResolveHeadTreeAsync(GitRepository repo)
    {
        var head = (await repo.ReferenceResolveAsync("HEAD")) as LibGit2CS.Refs.GitDirectReference;
        Assert.NotNull(head);
        Commit? commit = await repo.ObjectLookupAsync<Commit>(head.Target, TestContext.Current.CancellationToken);
        Assert.NotNull(commit);
        GitTree? tree = await repo.ObjectLookupAsync<GitTree>(commit.Tree, TestContext.Current.CancellationToken);
        Assert.NotNull(tree);
        return tree;
    }

    private static async Task<GitOid> ResolveFirstCommitOidAsync(GitRepository repo)
    {
        var headRef = (await repo.ReferenceResolveAsync("HEAD")) as LibGit2CS.Refs.GitDirectReference;
        Assert.NotNull(headRef);
        GitOid head = headRef.Target;
        Commit? commit = await repo.ObjectLookupAsync<Commit>(head, TestContext.Current.CancellationToken);
        Assert.NotNull(commit);
        IReadOnlyList<GitOid> parents = commit.Parents;
        return parents[0];
    }
}
